# Generated by Django 3.2.8 on 2024-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240325_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pos',
            field=models.CharField(default='Doctor', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='pos',
            field=models.CharField(default='Patient', max_length=10),
        ),
    ]
